export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR-ALERT'
export const NAVIGATE_PAGE = 'NAVIGATE_PAGE'

export const CREATE_PLACE_BEGIN = 'CREATE_PLACE_BEGIN'
export const CREATE_PLACE_SUCCESS = 'CREATE_PLACE_SUCCESS'
export const CREATE_PLACE_ERROR = 'CREATE_PLACE_ERROR'

export const GET_PLACES_BEGIN = 'GET_PLACES_BEGIN'
export const GET_PLACES_SUCCESS = 'GET_PLACES_SUCCESS'
export const GET_PLACES_ERROR = 'GET_PLACES_ERROR'

export const DELETE_PLACE_BEGIN = 'DELETE_PLACE_BEGIN'
export const DELETE_PLACE_SUCCESS = 'DELETE_PLACE_SUCCESS'
export const DELETE_PLACE_ERROR = 'DELETE_PLACE_ERROR'

export const SET_EDIT_PLACE = 'SET_EDIT_PLACE'

export const EDIT_PLACE_BEGIN = 'EDIT_PLACE_BEGIN'
export const EDIT_PLACE_SUCCESS = 'EDIT_PLACE_SUCCESS'
export const EDIT_PLACE_ERROR = 'EDIT_PLACE_ERROR'

export const TOGGLE_IS_REGISTERED = 'TOGGLE_IS_REGISTERED'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'
